version: '3'
services:
  backend:
    image: genome_backend
    build:
      context: ./server 
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app/server:rw
    ports:
      - "9000:9000"
    tty: true
    restart: always
  frontend:
    image: genome_frontend
    build:
      context: ./client 
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app/client:rw
    ports:
    - "3000:3000"
    environment:
      HOST: 0.0.0.0
      SHINY_URL: http://shiny:3838/
      kNOWSEQ_URL: http://knowseq:8787/
    tty: true
    restart: always
  shiny:
    image: shiny
    build:
      context: ./shiny
      dockerfile: Dockerfile
    restart: always
    environment:
      HOST: 0.0.0.0
    user: 'root'
    ports:
      - '3838:3838'
  knowseq:
    image: casedugr/knowseq
    ports:
      - "8787:8787"
    restart: always
    environment:
      PASSWORD: test
      HOST: 0.0.0.0
networks:
  default:
    external:
      name: genomebrowseq